/** Allowed `cloudConfig.services` values per provider (must stay in sync with client `scannerTypes.js`). */

export const CLOUD_SERVICES_BY_PROVIDER = {
  aws: [
    "s3",
    "ec2",
    "lambda",
    "rds",
    "dynamodb",
    "ecs",
    "eks",
    "iam",
    "sns",
    "sqs",
    "kms",
    "vpc",
    "cloudfront",
    "apigateway",
    "secretsmanager",
    "ecr",
    "elasticache",
    "cloudwatch",
    "route53",
    "redshift",
  ],
  azure: [
    "compute",
    "storage",
    "sql-database",
    "key-vault",
    "aks",
    "app-service",
    "functions",
    "networking",
    "cosmos-db",
    "monitor",
    "blob",
    "container-instances",
    "service-bus",
    "active-directory",
    "devops",
    "event-hubs",
    "redis-cache",
  ],
  gcp: [
    "compute-engine",
    "cloud-storage",
    "cloud-sql",
    "gke",
    "cloud-functions",
    "bigquery",
    "pub-sub",
    "iam",
    "vpc",
    "cloud-run",
    "secret-manager",
    "cloud-kms",
    "firestore",
    "cloud-monitoring",
    "cloud-build",
    "artifact-registry",
    "cloud-armor",
    "dns",
  ],
};

/** Allowed `cloudConfig.region` values per provider (must stay in sync with client `scannerTypes.js`). */
export const CLOUD_REGIONS_BY_PROVIDER = {
  aws: [
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
    "ap-south-1",
    "ap-south-2",
    "ap-southeast-1",
    "ap-southeast-2",
    "ap-southeast-3",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-northeast-3",
    "ca-central-1",
    "eu-central-1",
    "eu-central-2",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "eu-north-1",
    "eu-south-1",
    "eu-south-2",
    "sa-east-1",
    "me-south-1",
    "me-central-1",
    "af-south-1",
  ],
  azure: [
    "eastus",
    "eastus2",
    "westus",
    "westus2",
    "westeurope",
    "northeurope",
    "uksouth",
    "ukwest",
    "centralindia",
    "southindia",
    "japaneast",
    "koreacentral",
    "australiaeast",
    "canadacentral",
    "brazilsouth",
    "southafricanorth",
  ],
  gcp: [
    "us-central1",
    "us-east1",
    "us-east4",
    "us-west1",
    "us-west2",
    "us-west3",
    "us-west4",
    "europe-west1",
    "europe-west2",
    "europe-west3",
    "europe-west4",
    "europe-west9",
    "europe-west10",
    "asia-south1",
    "asia-south2",
    "asia-southeast1",
    "asia-southeast2",
    "asia-northeast1",
    "asia-northeast2",
    "asia-northeast3",
    "australia-southeast1",
    "southamerica-east1",
  ],
};

/** @param {string} provider */
export function cloudServicesSetForProvider(provider) {
  const list = CLOUD_SERVICES_BY_PROVIDER[provider];
  return list ? new Set(list) : null;
}

/** @param {string} provider */
export function cloudRegionsSetForProvider(provider) {
  const list = CLOUD_REGIONS_BY_PROVIDER[provider];
  return list ? new Set(list) : null;
}
