export const SCANNER_TYPES = ["docker", "sast", "aws", "azure", "gcp"];

export const SCANNER_TYPE_LABELS = {
  docker: "Container image",
  sast: "SAST (repository)",
  aws: "AWS",
  azure: "Azure",
  gcp: "GCP",
};

export const DOCKER_REGISTRIES = [
  { value: "dockerhub", label: "Docker Hub" },
  { value: "ecr", label: "Amazon ECR" },
  { value: "gcr", label: "Google GCR" },
  { value: "acr", label: "Azure ACR" },
  { value: "private", label: "Private registry" },
];

export const SAST_TOOLS = [
  { value: "semgrep", label: "Semgrep" },
  { value: "sonarqube", label: "SonarQube" },
  { value: "eslint", label: "ESLint" },
];

/** Static cloud regions per provider (IDs must match server `cloudServices.js`). Label: `code — friendly name` (codes match API casing). */
export const CLOUD_REGIONS = {
  aws: [
    { value: "us-east-1", label: "us-east-1 — US East (N. Virginia)" },
    { value: "us-east-2", label: "us-east-2 — US East (Ohio)" },
    { value: "us-west-1", label: "us-west-1 — US West (N. California)" },
    { value: "us-west-2", label: "us-west-2 — US West (Oregon)" },
    { value: "ap-south-1", label: "ap-south-1 — Asia Pacific (Mumbai)" },
    { value: "ap-south-2", label: "ap-south-2 — Asia Pacific (Hyderabad)" },
    { value: "ap-southeast-1", label: "ap-southeast-1 — Asia Pacific (Singapore)" },
    { value: "ap-southeast-2", label: "ap-southeast-2 — Asia Pacific (Sydney)" },
    { value: "ap-southeast-3", label: "ap-southeast-3 — Asia Pacific (Jakarta)" },
    { value: "ap-northeast-1", label: "ap-northeast-1 — Asia Pacific (Tokyo)" },
    { value: "ap-northeast-2", label: "ap-northeast-2 — Asia Pacific (Seoul)" },
    { value: "ap-northeast-3", label: "ap-northeast-3 — Asia Pacific (Osaka)" },
    { value: "ca-central-1", label: "ca-central-1 — Canada (Central)" },
    { value: "eu-central-1", label: "eu-central-1 — Europe (Frankfurt)" },
    { value: "eu-central-2", label: "eu-central-2 — Europe (Zurich)" },
    { value: "eu-west-1", label: "eu-west-1 — Europe (Ireland)" },
    { value: "eu-west-2", label: "eu-west-2 — Europe (London)" },
    { value: "eu-west-3", label: "eu-west-3 — Europe (Paris)" },
    { value: "eu-north-1", label: "eu-north-1 — Europe (Stockholm)" },
    { value: "eu-south-1", label: "eu-south-1 — Europe (Milan)" },
    { value: "eu-south-2", label: "eu-south-2 — Europe (Spain)" },
    { value: "sa-east-1", label: "sa-east-1 — South America (São Paulo)" },
    { value: "me-south-1", label: "me-south-1 — Middle East (Bahrain)" },
    { value: "me-central-1", label: "me-central-1 — Middle East (UAE)" },
    { value: "af-south-1", label: "af-south-1 — Africa (Cape Town)" },
  ],
  azure: [
    { value: "eastus", label: "eastus — East US" },
    { value: "eastus2", label: "eastus2 — East US 2" },
    { value: "westus", label: "westus — West US" },
    { value: "westus2", label: "westus2 — West US 2" },
    { value: "westeurope", label: "westeurope — West Europe" },
    { value: "northeurope", label: "northeurope — North Europe" },
    { value: "uksouth", label: "uksouth — UK South" },
    { value: "ukwest", label: "ukwest — UK West" },
    { value: "centralindia", label: "centralindia — Central India" },
    { value: "southindia", label: "southindia — South India" },
    { value: "japaneast", label: "japaneast — Japan East" },
    { value: "koreacentral", label: "koreacentral — Korea Central" },
    { value: "australiaeast", label: "australiaeast — Australia East" },
    { value: "canadacentral", label: "canadacentral — Canada Central" },
    { value: "brazilsouth", label: "brazilsouth — Brazil South" },
    { value: "southafricanorth", label: "southafricanorth — South Africa North" },
  ],
  gcp: [
    { value: "us-central1", label: "us-central1 — Iowa" },
    { value: "us-east1", label: "us-east1 — South Carolina" },
    { value: "us-east4", label: "us-east4 — Northern Virginia" },
    { value: "us-west1", label: "us-west1 — Oregon" },
    { value: "us-west2", label: "us-west2 — Los Angeles" },
    { value: "us-west3", label: "us-west3 — Salt Lake City" },
    { value: "us-west4", label: "us-west4 — Las Vegas" },
    { value: "europe-west1", label: "europe-west1 — Belgium" },
    { value: "europe-west2", label: "europe-west2 — London" },
    { value: "europe-west3", label: "europe-west3 — Frankfurt" },
    { value: "europe-west4", label: "europe-west4 — Netherlands" },
    { value: "europe-west9", label: "europe-west9 — Paris" },
    { value: "europe-west10", label: "europe-west10 — Berlin" },
    { value: "asia-south1", label: "asia-south1 — Mumbai" },
    { value: "asia-south2", label: "asia-south2 — Delhi" },
    { value: "asia-southeast1", label: "asia-southeast1 — Singapore" },
    { value: "asia-southeast2", label: "asia-southeast2 — Jakarta" },
    { value: "asia-northeast1", label: "asia-northeast1 — Tokyo" },
    { value: "asia-northeast2", label: "asia-northeast2 — Osaka" },
    { value: "asia-northeast3", label: "asia-northeast3 — Seoul" },
    { value: "australia-southeast1", label: "australia-southeast1 — Sydney" },
    { value: "southamerica-east1", label: "southamerica-east1 — São Paulo" },
  ],
};

/** Static cloud services per provider (IDs must match server `cloudServices.js`). */
export const CLOUD_SERVICES = {
  aws: [
    { value: "s3", label: "S3" },
    { value: "ec2", label: "EC2" },
    { value: "lambda", label: "Lambda" },
    { value: "rds", label: "RDS" },
    { value: "dynamodb", label: "DynamoDB" },
    { value: "ecs", label: "ECS" },
    { value: "eks", label: "EKS" },
    { value: "iam", label: "IAM" },
    { value: "sns", label: "SNS" },
    { value: "sqs", label: "SQS" },
    { value: "kms", label: "KMS" },
    { value: "vpc", label: "VPC" },
    { value: "cloudfront", label: "CloudFront" },
    { value: "apigateway", label: "API Gateway" },
    { value: "secretsmanager", label: "Secrets Manager" },
    { value: "ecr", label: "ECR" },
    { value: "elasticache", label: "ElastiCache" },
    { value: "cloudwatch", label: "CloudWatch" },
    { value: "route53", label: "Route 53" },
    { value: "redshift", label: "Redshift" },
  ],
  azure: [
    { value: "compute", label: "Virtual Machines" },
    { value: "storage", label: "Storage" },
    { value: "sql-database", label: "SQL Database" },
    { value: "key-vault", label: "Key Vault" },
    { value: "aks", label: "AKS" },
    { value: "app-service", label: "App Service" },
    { value: "functions", label: "Functions" },
    { value: "networking", label: "Networking" },
    { value: "cosmos-db", label: "Cosmos DB" },
    { value: "monitor", label: "Monitor" },
    { value: "blob", label: "Blob Storage" },
    { value: "container-instances", label: "Container Instances" },
    { value: "service-bus", label: "Service Bus" },
    { value: "active-directory", label: "Entra ID / AD" },
    { value: "devops", label: "Azure DevOps" },
    { value: "event-hubs", label: "Event Hubs" },
    { value: "redis-cache", label: "Redis Cache" },
  ],
  gcp: [
    { value: "compute-engine", label: "Compute Engine" },
    { value: "cloud-storage", label: "Cloud Storage" },
    { value: "cloud-sql", label: "Cloud SQL" },
    { value: "gke", label: "GKE" },
    { value: "cloud-functions", label: "Cloud Functions" },
    { value: "bigquery", label: "BigQuery" },
    { value: "pub-sub", label: "Pub/Sub" },
    { value: "iam", label: "IAM" },
    { value: "vpc", label: "VPC" },
    { value: "cloud-run", label: "Cloud Run" },
    { value: "secret-manager", label: "Secret Manager" },
    { value: "cloud-kms", label: "Cloud KMS" },
    { value: "firestore", label: "Firestore" },
    { value: "cloud-monitoring", label: "Cloud Monitoring" },
    { value: "cloud-build", label: "Cloud Build" },
    { value: "artifact-registry", label: "Artifact Registry" },
    { value: "cloud-armor", label: "Cloud Armor" },
    { value: "dns", label: "Cloud DNS" },
  ],
};
